- hosts: localhost
  tasks:
  - name: git fetch
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone git petclinic repo
    git: repo=https://github.com/spring-projects/spring-petclinic.git dest=/home/ec2-user/repo/petclinic
  - name: clone git trepo repo
    git: repo=https://github.com/ronialoni/trepo.git dest=/home/ec2-user/repo/trepo update=no
  - name: docker fetch
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: add user to a group
    user: name=ec2-user groups=docker append=yes
    become: yes
    become_method: sudo
  - name: start docker
    service: name=docker state=started
    become: yes
    become_method: sudo
  - name: get maven
    unarchive: copy=no creates=~/apache-maven-3.3.9 dest=~ src=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - name: Ensure Jenkins Yum repo present
    become: yes
    become_method: sudo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
           dest=/etc/yum.repos.d/jenkins.repo mode=0644
  - name: Ensure Jenkins GPG key installed
    command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    become: yes
    become_method: sudo
  - name: Ensure Jenkins installed
    yum: name=jenkins state=present
    become: yes
    become_method: sudo
  - name: Ensure Jenkins is running
    service: name=jenkins state=running enabled=true
    become: yes
    become_method: sudo
