FROM debian:jessie
MAINTAINER shimi
RUN apt-get update && apt-get install -y wget && wget http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz  && tar xvfz /apache-maven-3.3.9-bin.tar.gz


