FROM centos:6.8
MAINTAINER roni 
RUN mkdir ~/apache-maven-3.3.9
RUN cd ~/apache-maven-3.3.9
RUN curl -1 -k -O http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar -zxvf apache-maven-3.3.9-bin.tar.gz
