FROM centos:6.8
MAINTAINER roni 
RUN mkdir ~/apache-maven-3.3.9
ADD http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz ~/apache-maven-3.3.9
WORKDIR ~/apache-maven-3.3.9
RUN tar -zxvf apache-maven-3.3.9-bin.tar.gz
